{
 "title": "R-Keeper_Metrics-Part-2-V2",
 "description": "A dashboard to visualize the metrics from HTTP endpoints in Uptime Kuma",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "type",
    "query": {
     "query": "label_values(monitor_response_time, monitor_type)"
    }
   },
   {
    "name": "monitor",
    "query": {
     "query": "label_values(monitor_response_time{monitor_type=~\"$type\"}, monitor_name)"
    }
   },
   { "name": "tochka", "query": { "query": "label_values(monitor_name)" } }
  ]
 },
 "panels": [
  {
   "title": "PARKENT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"PARKENT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FERUZA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"FERUZA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MARKAZ-5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MARKAZ-5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YANGIYO'L-3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"YANGIYO'L-3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Urganch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"Urganch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BODOMZOR-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"BODOMZOR-2\", monitor_url=\"https://192.168.195.201:8085/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHORBOG",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"CHORBOG\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BUYUK IPAK",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"BUYUK IPAK\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BELTEPA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"BELTEPA\", monitor_url=\"https://192.168.208.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SHIFOKORLAR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"SHIFOKORLAR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ANDALUS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"ANDALUS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROHAT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"ROHAT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SHUHRAT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"SHUHRAT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHILONZOR SAVDO",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"CHILONZOR SAVDO\", monitor_url=\"https://192.168.204.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZANGIOTA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"ZANGIOTA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHORSU-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"CHORSU-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIGH TOWN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"HIGH TOWN\", monitor_url=\"https://192.168.212.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BERUNIY-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"BERUNIY-2\", monitor_url=\"https://192.168.209.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BAHODIR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"BAHODIR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NAMANGAN-4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"NAMANGAN-4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KO'KTERAK",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"KO'KTERAK\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MILLY BUYUK",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MILLY BUYUK\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MILLY QORASUV-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MILLY QORASUV-1\", monitor_url=\"https://192.168.130.204:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MILLY TOSHMI",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MILLY TOSHMI\", monitor_url=\"https://192.168.117.205:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MILLY OLMALIQ-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MILLY OLMALIQ-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SCOPUS MALL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"SCOPUS MALL\", monitor_url=\"https://192.168.221.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NAMANGAN-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"NAMANGAN-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URGUT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"URGUT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHIRCHIQ-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"CHIRCHIQ-2\", monitor_url=\"https://192.168.215.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SEOUL MUN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"SEOUL MUN\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OLMALIQ-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"OLMALIQ-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SERGELI-8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"SERGELI-8\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MILLY SERGELI-8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MILLY SERGELI-8\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MILLY AFRUZ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MILLY AFRUZ\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MILLY NOVZA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MILLY NOVZA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ANGREN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"ANGREN\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}