{
 "title": "R-Keeper_Metrics - Part 1",
 "description": "A dashboard to visualize the metrics from HTTP endpoints in Uptime Kuma",
 "panels": [
  {
   "title": "Golden Life",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"Golden Life\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TTZ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"TTZ\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DRUZHBA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"DRUZHBA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SERGELI YARMARKA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"SERGELI YARMARKA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FARHOD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"FARHOD\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SERGELI-5BEKAT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"SERGELI-5BEKAT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VODNIK",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"VODNIK\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QO'YLIQ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"QO'YLIQ\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RISOVIY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"RISOVIY\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHO’PON-OTA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"CHO’PON-OTA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YUNUSOBOD-5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"YUNUSOBOD-5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GULZOR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"GULZOR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WESTMINSTER",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"WESTMINSTER\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QATORTOL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"QATORTOL\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUTBINISO",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"QUTBINISO\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHILONZOR Metro",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"CHILONZOR Metro\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VATAN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"VATAN\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHILONZOR-19",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"CHILONZOR-19\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAKAT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"RAKAT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAJNUNTOL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MAJNUNTOL\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BERUNIY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"BERUNIY\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RIVIERA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"RIVIERA\", monitor_url=\"https://192.168.139.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LABZAK",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"LABZAK\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "XADRA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"XADRA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAGIC CITY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MAGIC CITY\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHORSUV",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"CHORSUV\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OXUNBOBOEV",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"OXUNBOBOEV\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BODOMZOR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"BODOMZOR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QORASUV-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"QORASUV-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LUNACHARSKIY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"LUNACHARSKIY\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OQTEPA MAYDONI",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"OQTEPA MAYDONI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LISUNOVA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"LISUNOVA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOSHMI",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"TASHMI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QORASUV-6",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"QORASUV-6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LISUNOVA-D",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"LISUNOVA-D\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KO'KSAROY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"KO'KSAROY\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QO'QON-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"QO'QON-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QO'QON-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"QO'QON-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHINOZ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"CHINOZ\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YANGIYO'L-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"YANGIYO'L-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YANGIYO'L-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"YANGIYO'L-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OLMALIQ-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"OLMALIQ-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UNIVERSAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"UNIVERSAM\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUKUS-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"NUKUS-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NURAFSHON",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"NURAFSHON\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUKUS-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"NUKUS-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FARG'ONA-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"FARG'ONA-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FARG'ONA-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"FARG'ONA-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "COMPASS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"COMPASS\", monitor_url=\"https://192.168.145.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NAMANGAN-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"NAMANGAN-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ALGORITM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"ALGORITM\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHIRCHIQ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"CHIRCHIQ\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YANGIBOZOR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"YANGIBOZOR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chig'atoy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"Chig'atoy\", monitor_url=\"https://192.168.184.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPODROM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"IPODROM\", monitor_url=\"https://192.168.126.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SAMARQAND-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"SAMARQAND-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QORAQAMISH",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"QORAQAMISH\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ANDIJON-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"ANDIJON-1\", monitor_url=\"https://192.168.175.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NAMANGAN-3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"NAMANGAN-3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "G'AZALKENT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"G'AZALKENT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Olim-Polvon",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"Olim-Polvon\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVIASOZLAR BOZORI",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"AVIASOZLAR BOZORI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SAMARQAND-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"SAMARQAND-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MINOR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MINOR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PISKENT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"PISKENT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ANDIJON-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"ANDIJON-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DOMBIROBOD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"DOMBIROBOD\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SAMARQAND-3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"SAMARQAND-3\", monitor_url=\"https://192.168.197.201:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QOYLIQ-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"QOYLIQ-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " BO'KA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"BO'KA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MARG'ILON",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"MARG'ILON\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUSHBEGI",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"QUSHBEGI\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}